[Runtime Security AG] CWP-39604
hlxsites/prisma-cloud-docs pull request #307
Opened 2024-01-08 14:56 UTC by anaghapamidi

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Ask: Remove any reference to the Incident types > Brute Force artciles. 

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--prisma-cloud-docs--hlxsites.hlx.page/
- After: https://<branch>--prisma-cloud-docs--hlxsites.hlx.page/
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=<branch>

2024-01-10 14:10 UTC, manukumar6 approved these changes

2024-01-10 17:34 UTC, rcaballeromx requested changes
It seems to me that you missed removing the link from some of the incident-types.adoc files in the following folders:

- 32/admin-guide
- runtime-security/

Other than that, it LGTM

2024-02-25 08:22 UTC, anaghapamidi commented
> It seems to me that you missed removing the link from some of the incident-types.adoc files in the following folders:
> 
> * 32/admin-guide
> * runtime-security/
> 
> Other than that, it LGTM

@rcaballeromx -  I have made these changes as requested. 
cc: @manukumar6

2024-02-26 03:26 UTC, manukumar6 approved these changes
Verified that the Brute Force topic is removed from all editions

2024-02-26 14:55 UTC, merged